spring.application.name=server

spring.datasource.url=jdbc:postgresql://csce-315-db.engr.tamu.edu:5432/team_30_db
spring.datasource.username=team_30
spring.datasource.password=construct90
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}




