# spring.application.name=server


# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver
# gemini.api.key=${GEMINI_API_KEY:}
# gemini.model=gemini-2.5-flash

# server.port=${PORT:8080}


spring.security.oauth2.client.registration.google.client-id=921918744604-0ohovsps2sthmt9oj98begiaaft13fdd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_API_KEY:}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google